dwallet-mpc: encrypt & send dWallet user share and Network DKG
dwallet-labs/ika pull request #432
Opened 2024-12-24 15:51 UTC by zeevmoney

2024-12-24 16:26 UTC, zeevmoney commented on pera-execution/latest/pera-adapter/src/execution_engine.rs
> +                // todo(zeev): need to clean this, also why is it different from batch sign?
@ItayLevyOfficial we need to talk about this one

2024-12-24 16:26 UTC, zeevmoney commented on crates/pera-node/src/lib.rs
> +        // todo(zeev): Itay, we should doc this and explain the diff from Manager.
@ItayLevyOfficial we need to talk about this

2024-12-24 17:05 UTC, ItayLevyOfficial approved these changes
lgtm

2024-12-24 17:05 UTC, ItayLevyOfficial commented on crates/pera-types/src/messages_dwallet_mpc.rs
> +    BatchedSign(Vec<MPCMessage>),
I think MPCMessage is not apt as this is a message the user provided to sign on, not a message sent between validators

2024-12-24 17:05 UTC, ItayLevyOfficial commented on crates/pera-types/src/messages_dwallet_mpc.rs
> +    BatchedSign(Vec<MPCMessage>),
not a big fan of this "type to explain field" practice in general, we'll better have structs for each round's inner data with descriptive field names

2025-01-12 10:36 UTC, ycscaly commented on crates/pera-core/src/dwallet_mpc/encrypt_user_share.rs
> +            .map_err(|e| DwalletMPCError::EncryptedUserShareVerificationFailed)?;
I think we wanted more than just the public user share signed, no?

2025-01-12 10:36 UTC, ycscaly commented on crates/pera-core/src/dwallet_mpc/encrypt_user_share.rs
> +        <Ed25519PublicKey as ToFromBytes>::from_bytes(&verification_data.encryptor_ed25519_pubkey)
Why it is a different field from `verify_encryption_key()`? And why is the logic duplicated snd the function not called?

2025-01-12 10:36 UTC, ycscaly commented on crates/pera-core/src/dwallet_mpc/encrypt_user_share.rs
> +/// Verifies that the given secret encryption is the encryption of the given dwallet's secret share.
```suggestion
/// Verifies that the given secret encryption is the encryption of the given dwallet's secret share by verifying a ZK proof that assures that.
```

2025-01-12 10:36 UTC, ycscaly commented on crates/pera-core/src/dwallet_mpc/encrypt_user_share.rs
> +        dkg_output.centralized_party_public_key_share,
Good

2025-01-12 10:36 UTC, ycscaly commented on crates/pera-core/src/dwallet_mpc/mod.rs
> +        .authority_by_index(party_id as u32 - 1)
Good, just add a comment

2025-01-13 07:56 UTC, ycscaly commented on crates/pera-core/src/dwallet_mpc/mpc_manager.rs
> +    ValidatorDataForDKG(ValidatorDataForDWalletSecretShare),
`ForDWalletSecretShare`? This name is confusing. Maybe `ForNetworkDKG`

2025-01-13 07:56 UTC, ycscaly commented on crates/pera-core/src/dwallet_mpc/mpc_manager.rs
> +        }
Probably better to this the opposite way: just save the mappying key by the authority pubkey.

2025-01-13 07:56 UTC, ycscaly commented on crates/pera-core/src/dwallet_mpc/mpc_manager.rs
> +            &AuthorityPublicKeyBytes::from_bytes(&data.protocol_pubkey_bytes)
Where do we verify that the sender who signed this message equals the pubkey that is written inside?

2025-01-13 07:56 UTC, ycscaly commented on crates/pera-core/src/dwallet_mpc/mpc_manager.rs
> +            "Decryption share not found".to_string(),
I don't like these names

2025-01-13 07:56 UTC, ycscaly commented on crates/pera-core/src/dwallet_mpc/mpc_manager.rs
> +    pub(super) fn get_decryption_public_parameters(
```suggestion
    pub(super) fn get_decryption_key_share_public_parameters(
```
You might think it helps using these shortened names, but it has the opposite effect of confusing auditors. Please use my original names every where

2025-01-13 07:56 UTC, ycscaly commented on crates/pera-core/src/dwallet_mpc/mpc_manager.rs
> +    fn get_decryption_share(
```suggestion
    fn get_decryption_key_shares(
```
`decryption_share` means something else entirely

2025-01-13 07:56 UTC, ycscaly commented on crates/pera-core/src/dwallet_mpc/mpc_manager.rs
> +                    MPCSessionStatus::Active => received_weight as StakeUnit >= threshold,
In previous pr I said to use the access structure method `is_authorized_subset` for this

2025-01-13 07:56 UTC, ycscaly commented on crates/pera-core/src/dwallet_mpc/mpc_manager.rs
> +                        .sum(),
Code duplication

2025-01-13 07:56 UTC, ycscaly commented on crates/pera-core/src/dwallet_mpc/mpc_manager.rs
> +                                .len();
We don't want validators to be able to DOS by preventing a DKG from happening by simply not supplying you with their `data_for_network_dkg`. Instead, you should pad it with default values for every validator that didn't send you this data; my code has validity checks, and will simply report that validator as malicious.

2025-01-13 07:56 UTC, ycscaly commented on crates/pera-core/src/dwallet_mpc/mpc_manager.rs
> +                                .len();
Alternatively, we can change my code to be able to get a partial mapping, or have the values as `Option` and report every missing player as malicious.

2025-01-13 07:56 UTC, ycscaly commented on crates/pera-core/src/dwallet_mpc/mpc_outputs_verifier.rs
>              >= self.quorum_threshold
Code duplication, use my method

2025-01-14 07:19 UTC, dolevmu reviewed
I release this before reviewing everything because I may be busy with 2pcmpc Scaly CRs. I viewed a lot of it.

2025-01-14 07:48 UTC, ycscaly requested changes
I'm stopping the review until suitable names are chosen for variables and types; the code is impossible to review in its current state. Use the names given in the original crypto crates.

Also, there is much missing documentation.

2025-01-14 07:48 UTC, ycscaly commented on crates/pera-core/src/dwallet_mpc/mpc_manager.rs
> +            DWalletMPCChannelMessage::ValidatorDataForDKG(data) => {
Remind self to think why it should be sent as such

2025-01-14 07:48 UTC, ycscaly commented on crates/pera-core/src/dwallet_mpc/mpc_session.rs
> +                if let AsynchronousRoundResult::Finalize { public_output, .. } = &result {
Please... add documentation. You're doing something very non-standard, that goes aside of every other party flow: explain why!

I know this is for encrypted user share, but most wouldn't get it immediately. This needs to be explained, and why it is here, and what is the purpose of this check in the grand scheme of things in relation to that feature.

@ItayLevyOfficial

2025-01-14 07:48 UTC, ycscaly commented on crates/pera-core/src/dwallet_mpc/mpc_session.rs
> +                        signed_public_share: event_data.signed_public_share.clone(),
Missing sig on network pub key share

2025-01-14 07:48 UTC, ycscaly commented on crates/pera-core/src/dwallet_mpc/mpc_session.rs
> +                        signed_public_share: event_data.signed_public_share.clone(),
Probably on its encrypted user share too. Refer to the original issue

2025-01-14 07:48 UTC, ycscaly commented on crates/pera-core/src/dwallet_mpc/mpc_session.rs
> +                        // Fields not relevant for verification; passing empty values.
So why are they there?

2025-01-14 07:48 UTC, ycscaly commented on crates/pera-core/src/dwallet_mpc/mpc_session.rs
> +                match verify_encrypted_share(verification_data) {
I wanted to ask: why is this here twice, once after DKG and once by its own. I know the design so I understood that this is for dWallet transfer where the other is for dWallet creation: but other won't! This must be documented

2025-01-14 07:48 UTC, ycscaly commented on crates/pera-core/src/dwallet_mpc/mpc_session.rs
> +                unreachable!("advance should never be called on a batched session")
Remind self to check this can never be reached even if other validators ir users behave maliciously

2025-01-14 07:48 UTC, ycscaly commented on crates/pera-core/src/dwallet_mpc/mpc_session.rs
> +            authority_name_to_party_id(&message.authority, &*self.epoch_store()?)?;
Signature verification happens before this right? We know `message.authority` signed this message?

2025-01-14 07:48 UTC, ycscaly commented on crates/pera-core/src/dwallet_mpc/mpc_session.rs
> +            authority_name_to_party_id(&message.authority, &*self.epoch_store()?)?;
Point us to where this occurs please

2025-01-14 07:48 UTC, ycscaly commented on crates/pera-core/src/dwallet_mpc/mpc_session.rs
> +        match self.pending_messages.get_mut(message.round_number) {
Good

2025-01-14 07:48 UTC, ycscaly commented on crates/pera-core/src/dwallet_mpc/mpc_session.rs
> +        let msg_len = self.pending_messages.len();
```suggestion
        let current_round = self.pending_messages.len();
```

2025-01-14 07:48 UTC, ycscaly commented on crates/pera-core/src/dwallet_mpc/mpc_session.rs
> +        let msg_len = self.pending_messages.len();
This is definitely a wrong name: `msg_len` means the length of a message, not of a vector of messages.

2025-01-14 07:48 UTC, ycscaly commented on crates/pera-core/src/dwallet_mpc/mpc_session.rs
> +            None if message.round_number == msg_len => {
This line exemplifies how bad of a name it is - look how confusing reading this is.

2025-01-14 07:48 UTC, ycscaly commented on crates/pera-core/src/dwallet_mpc/mpc_session.rs
>      pub(crate) fn handle_message(&mut self, message: &DWalletMPCMessage) -> DwalletMPCResult<()> {
I think this function is useless now, just delete it and call the inner function directly

2025-01-14 07:48 UTC, ycscaly commented on crates/pera-core/src/dwallet_mpc/network_dkg.rs
> +        // Safe to unwrap because the authority name is always present in the epoch store.
When you this kind of thing, it entails us needing to verify such complex assumptions, and I don't see the reason why not to return an error instead.

Think: an `unwrap` that fails throws an exception that halts the entire blockchain. This is a potential critical vulnerability. Auditors cannot ignore this. So we would have to go into Sui, and try to make sure under no condition this is possible - why waste our time on such useless endeavor, when you could have simply returned `Result`?

2025-01-14 07:48 UTC, ycscaly commented on crates/pera-core/src/dwallet_mpc/network_dkg.rs
> +            class_groups_decryption_key,
Where is this being taken from if the mock class group feature is disabled?

2025-01-14 07:48 UTC, ycscaly commented on crates/pera-core/src/dwallet_mpc/network_dkg.rs
All the names used throughout this file are completely false and misleading. This makes the code unreadable. I cannot audit this - please, stop inventing names for cryptographic variables, use their original names, I picked them for a purpose!

2025-01-14 13:06 UTC, zeevmoney commented on crates/dwallet-mpc-centralized-party/src/lib.rs
> +type SpecificEncryptionKey = EncryptionKey<
Please suggest a name.

2025-01-14 13:48 UTC, ycscaly commented on crates/dwallet-mpc-centralized-party/src/lib.rs
> +type SecretShareEncryptionProof = EncryptionOfDiscreteLogProofWithoutCtx<
```suggestion
type EncryptionOfSecretShareProof = EncryptionOfDiscreteLogProofWithoutCtx<
```

2025-01-15 12:30 UTC, ItayLevyOfficial commented on crates/dwallet-mpc-centralized-party/src/lib.rs
> +            )?))?)
@yaelAbergel

2025-01-16 21:06 UTC, zeevmoney commented on crates/dwallet-mpc-centralized-party/src/lib.rs
> +            let signed_message = bcs::to_bytes(&round_result.outgoing_message)?;
These are the messages (vector) signed by the centralized party, i think it should be named: "centralized_signed_messages"

2025-01-16 21:06 UTC, zeevmoney commented on crates/dwallet-mpc-centralized-party/src/lib.rs
> +                { FUNDAMENTAL_DISCRIMINANT_LIMBS },
Can't be done, it's from @ycscaly code.

2025-01-16 21:13 UTC, zeevmoney commented on crates/dwallet-mpc-centralized-party/src/lib.rs
> +    let protocol_public_params = protocol_public_parameters();
I don't think we can do someone about it in this code, we have to use these functions from the crypto libs.

2025-01-16 21:13 UTC, zeevmoney commented on crates/dwallet-mpc-centralized-party/src/lib.rs
> +        &mut OsRng,
Yes

2025-01-16 21:17 UTC, zeevmoney commented on crates/dwallet-mpc-centralized-party/src/lib.rs
> +}
This is called by the user, note that we are in the centralized party lib (Typescript->wasm)

2025-01-16 21:17 UTC, zeevmoney commented on crates/dwallet-mpc-centralized-party/src/lib.rs
> +pub fn decrypt_user_share_inner(
This is called by the user, note that we are in the centralized party lib (Typescript->wasm)

2025-01-16 22:57 UTC, zeevmoney commented on crates/dwallet-mpc-centralized-party/src/lib.rs
> +    let Some(plaintext): Option<<SpecificEncryptionKey as AdditivelyHomomorphicEncryptionKey<SCALAR_LIMBS>>::PlaintextSpaceGroupElement> = decryption_key
Not in this case.

│ error[E0282]: type annotations needed
│    --> /Users/zeevmanilovich/Dev/dwallet-network-new-main/crates/dwallet-mpc-centralized-party/src/lib.rs:364:10
│     |
│ 364 |         .into()
│     |          ^^^^
│ ...
│ 368 |     let secret_share_bytes = U256::from(&plaintext.value()).to_be_bytes().to_vec();
│     |                                          --------- type must be known at this point
│     |
│ help: try using a fully qualified path to specify the expected types
│     |
│ 362 ~     let Some(plaintext): Option<_> = <CtOption<group::secp256k1::Scalar> as Into<Option<_>>>::into(decryption_key
│ 363 ~         .decrypt(&ciphertext, &public_parameters))

2025-01-16 22:58 UTC, zeevmoney commented on crates/dwallet-mpc-centralized-party/src/lib.rs
> +    Ok(generator_group_element.scale(&Uint::<{ SCALAR_LIMBS }>::from_be_slice(&secret_share)))
it's not just bcs, need to change the scale function as I understand, please do a suggestion.

2025-01-19 03:06 UTC, ycscaly commented on crates/class-groups-constants/src/lib.rs
> +    let protocol_public_parameters = STANDARD.decode(&NETWORK_DKG_OUTPUT).unwrap();
rename at least

2025-01-19 03:08 UTC, ycscaly commented on crates/dwallet-mpc-centralized-party/src/lib.rs
> +    Ok(generator_group_element.scale(&Uint::<{ SCALAR_LIMBS }>::from_be_slice(&secret_share)))
why do you need to change it?

2025-01-19 03:52 UTC, ycscaly commented on crates/dwallet-mpc-centralized-party/src/lib.rs
> +                { FUNDAMENTAL_DISCRIMINANT_LIMBS },
impossible

2025-01-19 03:52 UTC, ycscaly commented on crates/dwallet-mpc-centralized-party/src/lib.rs
> +                { FUNDAMENTAL_DISCRIMINANT_LIMBS },
my code uses `SECP256K1_FUNDAMENTAL_DISCRIMINANT_LIMBS`. I dont export `FUNDAMENTAL_DISCRIMINANT_LIMBS` @zeevmoney

2025-01-19 03:56 UTC, ycscaly commented on crates/pera-framework/packages/pera-system/sources/dwallet.move
> +        centralized_output: vector<u8>,
Why is this saved here? It definitely shouldn't be.

2025-01-19 04:00 UTC, ycscaly commented on crates/pera-framework/packages/pera-system/sources/dwallet_2pc_mpc_ecdsa_k1.move
> +    /// - `centralized_public_key_share_and_proof`: The user (centralized) public key share and proof from the first round.
you can simply say its the user message

2025-01-19 04:01 UTC, ycscaly commented on crates/pera-framework/packages/pera-system/sources/dwallet_2pc_mpc_ecdsa_k1.move
> +            signed_public_share: signed_centralized_public_output,
No this is definitely wrong, why did you change it?

2025-01-19 05:16 UTC, ycscaly commented on crates/dwallet-classgroups-types/src/lib.rs
>      pub fn decryption_key(&self) -> ClassGroupsDecryptionKey {
rename it also to `decryption_key_per_crt_prime` so its consistent

2025-01-20 04:55 UTC, ycscaly commented on crates/dwallet-classgroups-types/src/lib.rs
> +    pub fn public(&self) -> ClassGroupsEncryptionKeyAndProof {
What does this name mean

2025-01-20 04:55 UTC, ycscaly commented on crates/dwallet-classgroups-types/src/lib.rs
> +        )
Where is `rng`

2025-01-20 04:55 UTC, ycscaly commented on crates/pera-core/src/dwallet_mpc/mpc_session.rs
> +                        session_id: ID::new(ObjectID::new([0; 32])),
What transcript

2025-01-20 04:55 UTC, ycscaly commented on crates/pera-core/src/dwallet_mpc/mpc_session.rs
> +                        session_id: ID::new(ObjectID::new([0; 32])),
You mean the protocol context? We've talked it through and you said we don't need anything external to the 2pc-mpc in there. Don't get me started

2025-01-20 04:55 UTC, ycscaly commented on crates/pera-core/src/dwallet_mpc/network_dkg.rs
> +        let class_groups_decryption_key =
+1

2025-01-20 04:55 UTC, ycscaly commented on crates/pera-core/src/dwallet_mpc/network_dkg.rs
> +                    secp256k1::GroupElement,
This of course would make this code non-generic, and would make it hard to integrate `ristretto` support. Generics are there to be used, not ignored.

2025-01-20 04:55 UTC, ycscaly commented on crates/pera-core/src/dwallet_mpc/network_dkg.rs
> +                    secp256k1::GroupElement,
Write your code using the same generics as I have, and then instantiate it once for `secp256k1` and once for `ristretto`

2025-01-20 04:55 UTC, ycscaly commented on crates/pera-core/src/dwallet_mpc/network_dkg.rs
> +        Vec<HashMap<PartyID, <AsyncProtocol as Protocol>::DecryptionKeyShare>>,
When you don't take `AsyncProtocol` to be generic here, you lose the entire purpose of this structure; you make a structure that is supposed to support multiple types of keys, but you use the type of a single specific key for it. How can it work?

2025-01-20 04:55 UTC, ycscaly commented on crates/pera-core/src/dwallet_mpc/network_dkg.rs
> +        Vec<HashMap<PartyID, <AsyncProtocol as Protocol>::DecryptionKeyShare>>,
Probably you should just save the `SecretKeyShareSizedNumber` here and create the decryption key share when you know the type for it

2025-01-20 15:44 UTC, zeevmoney commented on crates/dwallet-mpc-centralized-party/src/lib.rs
> +                { FUNDAMENTAL_DISCRIMINANT_LIMBS },
From you code:

<img width="801" alt="image" src="https://github.com/user-attachments/assets/e02597b1-c1bc-42d2-9853-e0f0d8aca045" />
but you also export `class_groups::SECP256K1_FUNDAMENTAL_DISCRIMINANT_LIMBS`
So I changed it.

2025-01-21 07:12 UTC, ycscaly reviewed
Network DKG looks overall good. Two big things:
1. The code now is not generic and wouldn't work for Ristretto because you are keeping the `DecryptionKeyShare` type in the mapping, which is specific to Secp256k1 as you took it from a given instantiation of `secp256k1::AsyncProtocol`.
You must instead save the raw `SecretKeyShareSizedNumber`.
2. You left as deferred work to only save the output after consesnsus was reached - can't defer this, has to be done.

2025-01-21 07:12 UTC, ycscaly commented on crates/pera-core/src/dwallet_mpc/network_dkg.rs
> +            malicious_parties: _,
LINK TO ISSUE

2025-01-21 07:12 UTC, ycscaly commented on crates/pera-core/src/dwallet_mpc/network_dkg.rs
> +            // Todo (#507): Save the output only after it has been verified first by quorum of validators.
Why aren't you doing this already?

2025-01-21 07:12 UTC, ycscaly commented on crates/pera-core/src/dwallet_mpc/network_dkg.rs
> +            // Todo (#507): Save the output only after it has been verified first by quorum of validators.
This has to be done immediately

2025-01-22 02:59 UTC, ycscaly commented on crates/pera-core/src/authority/authority_per_epoch_store.rs
>              EpochStartSystemState::V1(data) => data.get_decryption_key_shares(),
Is this only for the first epoch?

2025-01-22 02:59 UTC, ycscaly commented on crates/pera-core/src/authority/authority_per_epoch_store.rs
>                          // TODO (#382): Decrypt the decryption key share
How is this not implemented, yet the network DKG feature is considered done?

2025-01-22 02:59 UTC, ycscaly commented on crates/pera-core/src/consensus_handler.rs
> +                                    // as it requires the class-groups crate from crypto-private lib.
I don't understand

2025-01-22 02:59 UTC, ycscaly commented on crates/pera-core/src/dwallet_mpc/mpc_manager.rs
> +        let decryption_shares = epoch_store
```suggestion
        let decryption_key_shares = epoch_store
```

2025-01-22 02:59 UTC, ycscaly commented on crates/pera-core/src/dwallet_mpc/mpc_manager.rs
> +        let decryption_shares = epoch_store
@zeevmoney

2025-01-22 02:59 UTC, ycscaly commented on crates/pera-core/src/dwallet_mpc/mpc_manager.rs
> +        if let Some(self_decryption_share) = self.epoch_store()?.dwallet_mpc_network_keys.get() {
```suggestion
        if let Some(self_decryption_key_share) = self.epoch_store()?.dwallet_mpc_network_keys.get() {
```

2025-01-22 02:59 UTC, ycscaly commented on crates/pera-core/src/dwallet_mpc/mpc_manager.rs
> +            "Decryption share not found".to_string(),
```suggestion
            "Decryption key share not found".to_string(),
```

2025-01-22 02:59 UTC, ycscaly commented on crates/pera-core/src/dwallet_mpc/mpc_manager.rs
>              return Ok(());
I don't agree with this at all

2025-01-22 17:12 UTC, yaelAbergel commented on crates/dwallet-classgroups-types/src/lib.rs
> +); MAX_PRIMES];
Did you do it?
Notice that I am using different `ClassGroupsProof` types for mocking

2025-01-23 08:50 UTC, yaelAbergel commented on crates/dwallet-classgroups-types/src/lib.rs
> +                .unwrap();
When could the Class Groups key generation fail?
In any case, we only use this function before the validator joins the network, and the validator cannot join the network without the Class Groups encryption key and proof.

2025-01-29 13:04 UTC, cdesaintguilhem reviewed
In `dwallet-mpc-centralized-party/lib.rs` there is an encryption key passed into an argument that is called "public parameters". This might be correct from the code's perspective, but it's confusing to read.

2025-01-29 13:04 UTC, cdesaintguilhem commented on crates/pera-framework/packages/pera-system/sources/dwallet.move
> +    /// Each address on the dWallet Network is associated with a unique encryption key.
Is "dWallet Network" the right name?

2025-01-29 13:04 UTC, cdesaintguilhem commented on crates/pera-framework/packages/pera-system/sources/dwallet.move
Why is all the code about the `EncryptionKey` objects in the same module as the `DWallet` objects? Should they not be in their own module?

2025-02-02 10:18 UTC, dolevmu reviewed
I focused on the state sync.

2025-02-02 10:18 UTC, dolevmu commented on sdk/typescript/test/e2e/encrypt-user-share.test.ts
> +});
Do we want to run a test also for non-happy flows? Like, a client shares a wrong share, or invalid proof, or a validator states the proof to be invalid although it is valid, to try to frame, etc.? I think currently tests are mostly to see everything is working when everyone is honest, correct me if I am wrong.

The most important thing to test of course is state sync, and that malicious parties cannot stall the network or make a session fail to finish.

2025-02-02 10:18 UTC, dolevmu commented on crates/pera-core/src/authority/authority_per_epoch_store.rs
> +    /// round.
Maybe mention why it is okay and we are not afraid a malicious party will bloat the memory of validators.

2025-02-06 12:13 UTC, yaelAbergel commented on Cargo.toml
> +twopc_mpc = { git = "https://github.com/dwallet-labs/cryptography-private", subdir = "2pc-mpc", features = ["secp256k1", "bulletproofs", "paillier", "class_groups", "benchmarking"], branch = "pera-ne
https://github.com/dwallet-labs/dwallet-network/issues/605

2025-02-06 12:13 UTC, yaelAbergel commented on Cargo.toml
> +twopc_mpc = { git = "https://github.com/dwallet-labs/cryptography-private", subdir = "2pc-mpc", features = ["secp256k1", "bulletproofs", "paillier", "class_groups", "benchmarking"], branch = "pera-ne
https://github.com/dwallet-labs/dwallet-network/issues/605

2025-02-06 12:20 UTC, yaelAbergel commented on crates/dwallet-classgroups-types/src/lib.rs
> +    #[cfg(feature = "mock-class-groups")]
Added todo... We must use it for development so that testing the code won't take forever.

2025-02-06 12:49 UTC, yaelAbergel commented on crates/pera-core/src/dwallet_mpc/mpc_manager.rs
> +        }
Why? Eventually we pass the map as a parameter to the `advance` function of the network DKG and it uses `PartyID`...

2025-02-17 13:52 UTC, cdesaintguilhem commented on crates/pera-core/src/dwallet_mpc/mpc_manager.rs
> +                .available_cores_for_cryptographic_computations
Couldn't this be written as

```suggestion
        while self
            .cryptographic_computations_orchestrator
            .has_available_core()
```

2025-02-17 14:35 UTC, cdesaintguilhem reviewed
A session that fails to spawn is lost because it was already popped from the list of sessions waiting for computation.

2025-02-17 14:35 UTC, cdesaintguilhem commented on crates/pera-core/src/dwallet_mpc/mpc_manager.rs
> +    /// Restarted for each epoch.
I think it's relatively okay since a party can only be malicious once per epoch. If they are malicious many times, then they should be losing a lot of rewards and the market will remove them from the set of validators.

2025-02-17 14:35 UTC, cdesaintguilhem commented on crates/pera-core/src/dwallet_mpc/sign.rs
> +pub(crate) const SIGN_LAST_ROUND_COMPUTATION_CONSTANT_SECONDS: usize = 15;
Indeed using SUI's built-in mechanism would be cleaner.

2025-02-18 13:03 UTC, cdesaintguilhem approved these changes

2025-02-18 13:03 UTC, cdesaintguilhem approved these changes

2025-05-28 17:24 UTC, closed without merging

2025-05-28 17:25 UTC, zeevmoney commented
This is an old version, before changing the architecture of the blockchain, it is now `ika`.